### Ejercicios de NumPy
1.  Importa la librería de NumPy.
2. Crea un array de 1 dimension y 10 elementos.
3.  Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.
4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.


In [1]:
# importamos numpy

import numpy as np


In [2]:
# creamos el array com elementos aleatorios com randint

a = np.random.randint(0,10, (10))

a

array([6, 2, 2, 0, 8, 7, 7, 2, 7, 5])

In [3]:
# creamos un array vacio para poner los elemntos los que vamos a iterar

a_vacio = np.empty_like(a, dtype = "U5")

a_vacio

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U5')

In [4]:
a

array([6, 2, 2, 0, 8, 7, 7, 2, 7, 5])

In [5]:
#iteramos los elementos de a para ponerlos en el array vacio que hemos creado de acuerdo con las condiciones impuestas en el bulce 

for i in range(0,a.shape[0]):
    if a[i] % 2 == 0:
        a_vacio[i] = "PAR"
    else:
         a_vacio[i] = "IMPAR"
         
print(a_vacio)

['PAR' 'PAR' 'PAR' 'PAR' 'PAR' 'IMPAR' 'IMPAR' 'PAR' 'IMPAR' 'IMPAR']


In [6]:
# con reshape cambiamos la forma del array vacio (podríamos haber utilizado también el método transpose)

a_vacio.shape

a_reshape = np.reshape(a_vacio, (2, 5))

a_reshape

array([['PAR', 'PAR', 'PAR', 'PAR', 'PAR'],
       ['IMPAR', 'IMPAR', 'PAR', 'IMPAR', 'IMPAR']], dtype='<U5')

5. Extrae los elementos comunes de los siguientes arrays

In [7]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
array1

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [9]:
array2

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [10]:
np.intersect1d(array1, array2)

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.
7. Extraed las posiciones donde tengamos elementos que sean iguales.
8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.
9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.
10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20
- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [11]:
# 6. con setdiff1d extraemos los elementos que están en el array1 pero no en el array2

np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

In [18]:
# 7. con npwhere extraemos los elementos que son iguales en los dos arrays

array1

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [20]:
print(f' el numero 2 está en las posiciones {np.where(array1 == 2)}')
print(f' el numero 3 está en las posiciones {np.where(array1 == 3)}')
print(f' el numero 4 está en las posiciones {np.where(array1 == 4)}')



 el numero 2 está en las posiciones (array([1, 3]),)
 el numero 3 está en las posiciones (array([2, 4, 6]),)
 el numero 4 está en las posiciones (array([5, 7]),)


In [19]:
array2

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [21]:
print(f' el numero 2 está en las posiciones {np.where(array2 == 2)}')
print(f' el numero 4 está en las posiciones {np.where(array2 == 4)}')
print(f' el numero 7 está en las posiciones {np.where(array2 == 7)}')
print(f' el numero 9 está en las posiciones {np.where(array2 == 9)}')

 el numero 2 está en las posiciones (array([1, 3]),)
 el numero 4 está en las posiciones (array([5, 7]),)
 el numero 7 está en las posiciones (array([0, 4]),)
 el numero 9 está en las posiciones (array([6, 8]),)


In [24]:
# 8. con randint creamos un array con 3 filas y 5 columnas de 0-50

array3 = np.random.randint(0,50, (3, 5))

print(array3)

# aplicamos los filtros conforme lo que pide el enunciado

array3[(10>array3) | (array3>40)]

[[40 20 41  4 47]
 [46 29 18 35 17]
 [14 49 10 18 11]]


array([41,  4, 47, 46, 49])

In [22]:
# 9. creamos un array de 5 lineas y 3 columnas con números aleatorios decimales entre 5 y 10 con random.uniform

array4 = np.random.uniform(low=5, high=10, size=(5,3))

array4 

array([[7.17312972, 8.1435764 , 5.13803844],
       [9.90101485, 9.65829017, 5.66053791],
       [5.49906656, 7.84774879, 8.07313878],
       [9.6703634 , 7.26847702, 9.49443363],
       [6.71454134, 7.94423585, 9.74385044]])

In [23]:
# 10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20. 


array5 = np.random.randint(1, 20, (2,4,7))

array5 

# Transponemos el array para que tuviera 4 matrices, 7 filas y 2 columnas cambiando los índices del array 

array6 = np.transpose(array5, (1,2,0))

array6

array([[[11, 18],
        [17,  9],
        [ 6,  8],
        [ 3,  3],
        [ 8, 13],
        [ 3,  4],
        [ 9, 12]],

       [[ 5,  1],
        [13, 13],
        [ 8,  5],
        [ 9,  3],
        [14, 11],
        [15,  2],
        [11, 12]],

       [[16,  1],
        [17,  6],
        [19,  9],
        [ 2,  4],
        [ 4, 10],
        [ 1, 10],
        [14,  1]],

       [[14,  3],
        [16,  2],
        [19, 15],
        [ 7, 17],
        [ 1,  7],
        [ 3, 12],
        [16, 18]]])